FROM php:8.5-fpm

ENV OPCACHE_VALIDATE_TIMESTAMPS=0

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
    && apt update && apt install -y nginx \
    && install-php-extensions intl apcu zip mongodb xdebug

RUN ln -s ${PHP_INI_DIR}/php.ini-production ${PHP_INI_DIR}/php.ini \
    && sed -i -e "s/^ *memory_limit.*/memory_limit = 512M/g"  ${PHP_INI_DIR}/php.ini

COPY docker/php/conf.d/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
COPY docker/php/conf.d/meal-planner.ini ${PHP_INI_DIR}/conf.d/meal-planner.ini

WORKDIR /var/www/html

COPY docker/nginx/conf.d/default.dev.conf /etc/nginx/conf.d/default.conf

CMD ["php-fpm"]

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer

RUN set -xe; \
    mkdir ~/.composer;

COPY app /var/www/html
RUN composer install --prefer-dist --no-progress --no-suggest -o --no-interaction --ignore-platform-reqs

COPY docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

VOLUME /var/www/html

ENTRYPOINT ["docker-entrypoint"]
